name: flowup

services:
  app:
    container_name: app
    depends_on:
      - api
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app/src:/var/www/html
    ports:
      - "4000:80"
    environment:
      API_BASEURL: http://localhost:4001
    

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flowup
    ports:
      - "4002:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
  

  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./api/src:/app
    ports:
      - "4001:3000"
    environment:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: flowup
      DB_PORT: 4002
    command: ["npm", "run", "dev"]  # Lancement automatique d'Express.js